apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- python-test-deployment.yaml
- python-test-ingress.yaml
- python-test-svc.yaml
- hpa.yaml

# replicas:
# - count: 2
#   name: python-test
    
images:
- name: hutinskit/python-test-app
  newTag: 1.0.146
