apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJodXRpbnNraXQiLCJwYXNzd29yZCI6IjRPb1E5dWkxb203ZyIsImVtYWlsIjoidGluby5odXRpbnNraUBnbWFpbC5jb20iLCJhdXRoIjoiYUhWMGFXNXphMmwwT2pSUGIxRTVkV2t4YjIwM1p3PT0ifX19
type: kubernetes.io/dockerconfigjson
